# ENV['DATABASE_URL'] can override these values

# common options apply to all environments
common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *common
  database: entryapplication_development
  username: entryapplication_development
  password: entryapplication_development
  pool: 5
test:
  <<: *common
  database: entryapplication_test
  username: entryapplication_test
  password: entryapplication_test
  pool: 5
production:
  <<: *common
  database: entryapplication_production
  username: entryapplication_production
  password: entryapplication_production
  pool: 5
